### ISSUE TITLE
Document how to use plugin in code

### ISSUE THREAD

**Issue by dene14** [jenkinsci/multibranch-action-triggers-plugin#12]
Would be useful to have examples how to use that plugin in pipeline code or "configuration as a code" jenkins plugin.

Thank you!

**Comment by aytuncbeken** [comment]
Hey, 
I will provide an example and update the Readme

**Comment by aytuncbeken** [comment]
Hi @dene14 ,
You can find the Job DSL usage in the Readme. https://github.com/jenkinsci/multibranch-action-triggers-plugin
Best.
