### ISSUE TITLE
It's not a bug I am just trying to figure out how to create this multicranch using only jenkinsfile

### ISSUE THREAD

**Issue by gabrielpasv** [jenkinsci/multibranch-action-triggers-plugin#13]
**Describe the bug**
It's not a bug I am just trying to figure out how to create this multicranch using only jenkinsfile. I need to add k8s clean up commands after delete a branch.
Right now when a branch is deleted, the associate jenkins job for that branch is also deleted. I want to be able to run some k8s clean up commands.

**Comment by ShreyasSubhedar** [comment]
Same I also want somewhat similar
