### ISSUE TITLE
REQUEST FO JOINING THE JENKINS ORGANISATION

### ISSUE THREAD

**Issue by akshitagupta15june** [jenkinsci/multibranch-action-triggers-plugin#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aytuncbeken** [comment]
I think, this is not right place for this issue.

**Comment by akshitagupta15june** [comment]
@aytuncbeken can you guide where should i put this issue

**Comment by akshitagupta15june** [comment]
I want to join the org
